/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parteGrafica;

import nasf.Paciente;

/**
 *
 * @author aluno
 */
public class PacienteGraf extends javax.swing.JFrame {

    /**
     * Creates new form Paciente
     */
    Paciente paciente;
    public PacienteGraf(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        atualizarTela();
    }
    
    
    public void atualizarTela(){
        txtNomePaciente.setText(this.paciente.getNome());
        txtIdadePaciente.setText(this.paciente.getIdade() + "");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePaciente = new javax.swing.JLabel();
        txtIdadePaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNomePaciente.setText("jLabel1");

        txtIdadePaciente.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdadePaciente)
                    .addComponent(txtNomePaciente))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtNomePaciente)
                .addGap(18, 18, 18)
                .addComponent(txtIdadePaciente)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtIdadePaciente;
    private javax.swing.JLabel txtNomePaciente;
    // End of variables declaration//GEN-END:variables
}
